export interface snacksArr{
    name:string
    sku:number
    active:boolean
    quantity:number
    images:[
        {
            file:{
                id:string
                date_uploaded:string
                length:number
                md5:string
                filename:number
                content_type:string
                metadata:number
                url:string
                width:number
                height:number
            }
            id:string
        },
        {
            file:{
                id:string
                date_uploaded:string
                length:number
                md5:string
                filename:number
                content_type:string
                metadata:number
                url:string
                width:number
                height:number
            }
            id:string
        }
    ]
    bundle:boolean
    sale:boolean
    price:number
    sale_price:number
    variable:boolean
    description:string
    meta_title:number
    meta_description:number
    slug:string
    attributes:{
        ingredients:string
    }
    type:string
    stock_tracking:boolean
    currency:string
    delivery:string
    tax_class:string
    date_created:string
    stock_status:number
    date_updated:string
    id:string
}